version: '2'

services:
  privoxy:
    build: .
    container_name: privoxy
    restart: always
    network_mode: host
    volumes:
      # - ./privoxy/config:/etc/privoxy/config
      - ./privoxy-blocklist.conf:/privoxy-blocklist.conf

    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.8:514"
