version: '2'

services:
  privoxy:
    build: .
    container_name: privoxy
    restart: always
    network_mode: host
    volumes:
      - ./privoxy-blocklist.conf:/privoxy-blocklist.conf
    extra_hosts:
      - "mammoth:192.168.1.8"
