version: '2.3'

services:
  privoxy:
    build: .
    container_name: privoxy
    restart: always
    network_mode: host
    volumes:
      - ./privoxy-blocklist.conf:/privoxy-blocklist.conf
    healthcheck:
      test: bash -c ">/dev/tcp/127.0.0.1/8118"

